### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by Robbybp** [lanl-ansi/JuMPIn.jl#14]
JuMP is trademarked. We need to use a different name. Possibilities:
- MathProgIncidence
- MathOptIncidence
- IncidenceOpt
- IncidenceAnalysis.jl
- Math Programming Incidence Analysis (MAPINA or MAPRINA for short)
- Analyzing incidence of Math Programs (AMP, AMP-Incidence, IncidenceAMP)

What does the package do?
- Construct incidence graphs from optimization models
- Implement decompositions
- Potentially: implement solvers based on these decompositions

| Name | Pros | Cons |
| ---- | ---- | ---- |
| MathProgIncidence | Describes the package well | Wordy, would probably be imported as MPI |
| MathOptIncidence | ^same | Too close to MathOptInterface? |
| IncidenceOpt | More concise, import abbreviation is not as overloaded | Maybe sounds like a solver? Too close to InfiniteOpt? | 
| IncidenceAnalysis.jl | Describes package well; import abbreviation not overloaded | Same name as Pyomo extension with same purpose |
| MAPINA | Imports well, unique | Abbreviation |
| AMP/IncidenceAMP | Imports well | Semi-abbreviated | 

### Cons of a too-general name

A potential issue with using "MathProg", "MathOpt", or "Opt" is that people may assume that this package works with other, non-JuMP optimization environments in Julia. It could be extended to analyze, for instance, optimization models from `NLPModels.jl`, but that is not my intent at the moment. For some reason I think "MathProgIncidence" is better in this regard. Probably because I associate "mathematical programming" with using an algebraic modeling language. We could import with `import MathProgIncidence as MaPrIn` to avoid overloading "MPI"?

### Cons of using same name as Pyomo implementation

I like `IncidenceAnalysis.jl`, but the Pyomo implementation of the same functionality is already `pyomo.contrib.incidence_analysis`. Statements like "Incidence Analysis can do X" will become ambiguous, which seems no good.

### Cons of abbreviations

Hard to remember, nobody knows what they stand for.

### Conclusions
I'm currently leaning towards "MathProgIncidence" or "IncidenceAMP"

**Comment by ccoffrin** [comment]
Does the package reason at the level of JuMP models or MOI models?  In the former I think `MathProgIncidence` is a good choice, in the later, I think `MathOptIncidence` would fit nicely with the current ecosystem naming conventions.

**Comment by Robbybp** [comment]
It operates at the JuMP level. I think I'll go with `MathProgIncidence`.

**Comment by Robbybp** [comment]
Renaming the package will require:
- [ ] Update Project.toml and JuMPIn.jl
- [ ] Update imports in code: `import JuMPIn: ...`
- [ ] Update examples in docstrings: `import JuMPIn as ji`,  `ji.IncidenceGraphInterface`, etc.
- [ ] Update README: title, example, text
- [ ] Update docs: example, landing page, `sitename` in `make.jl`
- [ ] Update name of the github repository

Then the package can be registered.
